name: Kali-Light

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: Build Kali-Linux
        run: |
          mingw32-make CFLAGS=-O3
          
      - name: Upload Kali ISO
        uses: actions/upload-artifact@v2
        with:
          name: Kali
          path: flips.exe
